[package]
name = "pubky-tls-proxy"
version = "0.3.4"
edition = "2021"

[dependencies]
pkarr = { version = "8.0.2", features = ["full"] }
tokio = { version = "1.44.2", features = ["full"] }
tokio-rustls = "0.26.0"
anyhow = "1.0.86"
clap = { version = "4.5.8", features = ["derive"] }
hex = "0.4.3"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
rustls = { version = "0.23.28", default-features = false, features = ["std"] }
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.1.6"
url = "2"
futures-util = { version = "0.3", default-features = false, features = ["std"] }
tempfile = "3.27.0"

[dev-dependencies]
reqwest = { version = "0.13", features = ["rustls"], default-features = false }
portpicker = "0.1.1"
once_cell = "1.19.0"
tokio-test = "0.4"
rustls = { version = "0.23.28", default-features = false, features = ["std", "ring"] }
mainline = "8"
